version: '3.3'
services:
  edu-campus:
    container_name: edu-campus
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/edu-campus
    working_dir: /usr/src/edu-campus

    networks:
      - client-network

    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
