export enum CourseType {
	BEGINNER = 'BEGINNER',
	INTERMEDIATE = 'INTERMEDIATE',
	ADVANCED = 'ADVANCED',
}

export enum CourseStatus {
	ACTIVE = 'ACTIVE',
	SOLD = 'SOLD',
	INACTIVE = 'INACTIVE',
	DELETE = 'DELETE',
}

export enum CourseCategory {
	JAVASCRIPT = 'JAVASCRIPT',
	TYPESCRIPT = 'TYPESCRIPT',
	PYTHON = 'PYTHON',
	WEB_DEVELOPMENT = 'WEB_DEVELOPMENT',
	MOBILE_DEVELOPMENT = 'MOBILE_DEVELOPMENT',
	DATA_SCIENCE = 'DATA_SCIENCE',
	UI_UX_DESIGN = 'UI_UX_DESIGN',
	DEVOPS = 'DEVOPS',
}
